In [7]:
import math

import numpy as np

import torch
from torch import nn

from tinygrad import Tensor
from tinygrad import nn as nn_tg


ImportError: cannot import name 'Tensor' from 'tinygrad' (/Users/saugatmalla/Documents/Projects/tinygrad/tinygrad/tinygrad/__init__.py)

### GELU

In [8]:
## Custom
input = torch.tensor([-3., -2., -1., 0., 1., 2., 3.])
gelu_py = 0.5 * input * (1.0 + torch.tanh( math.sqrt(2.0/math.pi) * (input + (0.044715 * (np.power(input, 3.0) )) )) ) 
print(gelu_py)

## Pytorch
#input = torch.randn(2)
input = torch.tensor([[-3., -2., -1., 0., 1., 2., 3.]])
print(f"Input:{input}")
gelu_pt = nn.GELU()
print(gelu_pt(input))
gelu_pt = nn.GELU(approximate='tanh')
print(gelu_pt(input))


## Tinygrad
print(Tensor([-3., -2., -1., 0., 1., 2., 3.]).gelu().numpy()) # GELU
print(Tensor([[-3., -2., -1., 0., 1., 2., 3.]]).quick_gelu().numpy()) # Quick_GELU


tensor([-0.0036, -0.0454, -0.1588,  0.0000,  0.8412,  1.9546,  2.9964])
Input:tensor([[-3., -2., -1.,  0.,  1.,  2.,  3.]])
tensor([[-0.0040, -0.0455, -0.1587,  0.0000,  0.8413,  1.9545,  2.9960]])
tensor([[-0.0036, -0.0454, -0.1588,  0.0000,  0.8412,  1.9546,  2.9964]])


NameError: name 'Tensor' is not defined